### PR TITLE
add phatomjsArgs

### PR DESCRIPTION
**Pull request by yoshi6jp**
added phantomjsArgs options.

### CODE REVIEW

**Comment by cognitom** [comment]
Thanks! Basically LGTM 👍 
Have you considered to use an object like this? :

``` javascript
export.config = {
  // ...
  services: ['phantomjs'],
  phantomjsOpts: {
    webdriverLogfile: 'phantomjs.log',
    ignoreSslErrors: true
  }
  // ...
}
```

PhantomJS provides the way via `config.json` so we could follow the naming convention of that.
http://phantomjs.org/api/command-line.html#command-line-options

**Comment by yoshi6jp** [comment]
In my opinion 

``` js
export.config = {
  // ...
  services: ['phantomjs'],
  phantomjsArgs: [
    '--config=/path/to/config.json'
  ]
  // ...
}
```

``` json
{
  "ignoreSslErrors": true
}
```

**Comment by cognitom** [comment]
[wdio-sauce-service](https://github.com/webdriverio/wdio-sauce-service) handles options well. They convert `--arg` to `{ option }` here:
https://github.com/bermi/sauce-connect-launcher/blob/master/lib/process_options.js

We'd rather follow them?

**Comment by cognitom** [comment]
Super cool! Thanks.
I'm merging this.

**Comment by cognitom** [comment]
@yoshi6jp now version 0.2.2 has been published 😄 

Because of some issues (#3, #4), it took a time.

**Pull request merged**
